## Application of CNN on NHANES dataset due to the understanding of data complexity. (Overkill model)

In [1]:
# Mount google drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
# Set directory path
import os
os.chdir("/content/drive/My Drive/COMP-5800-YDK-2020_Group1")

In [3]:
import pandas as pd
import numpy as np

In [4]:
demoData = pd.read_csv('HybridDatasets/DemographicsData.csv')
dietData = pd.read_csv('HybridDatasets/DietaryData.csv')
examData = pd.read_csv('HybridDatasets/ExaminationData.csv')
labData = pd.read_csv('HybridDatasets/LaboratoryData.csv')
questionData = pd.read_csv('HybridDatasets/QuestionnaireData.csv')
hypertensionData = pd.read_csv('HybridDatasets/HypertensionData.csv')

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (40,44,45,49,50,54,55,56,57,58,59,64,67,69,72,74,75,76,77,80,81,82,83,84,85,87,89) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [5]:
import keras
import tensorflow as tf
from keras.models import Sequential, Input, Model
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv1D, MaxPooling1D, LeakyReLU
from keras.layers.normalization import BatchNormalization

Demographics Feature Extraction

In [6]:
demoData.shape

(8366, 30)

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
demoX_train, demoX_test, demoY_train, demoY_test = train_test_split(demoData, hypertensionData['Target'], test_size=0.33, random_state=42)

In [9]:
model = Sequential()
model.add(Conv1D(256, 3, activation='relu', input_shape=(30, 1)))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='relu'))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='relu'))     
model.add(MaxPooling1D(2))
model.add(Flatten(name='layer1'))
output1 = model.output
# model.add(Dense(128, activation='relu', name='layer1'))
# print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='adamax', metrics=['accuracy'])

In [10]:
output1

<KerasTensor: shape=(None, 128) dtype=float32 (created by layer 'layer1')>

In [11]:
demoX_train = demoX_train.to_numpy()
demoX_train = demoX_train.reshape(demoX_train.shape[0], demoX_train.shape[1], 1)
demoX_test = demoX_test.to_numpy()
demoX_test = demoX_test.reshape(demoX_test.shape[0], demoX_test.shape[1], 1)
model.fit(demoX_train, demoY_train, epochs=50, batch_size=128)

Epoch 1/50
44/44 [==============================] - 2s 39ms/step - loss: 3.4215 - accuracy: 0.7373
Epoch 2/50
44/44 [==============================] - 2s 38ms/step - loss: 2.9798 - accuracy: 0.8068
Epoch 3/50
44/44 [==============================] - 2s 38ms/step - loss: 2.9922 - accuracy: 0.8060
Epoch 4/50
44/44 [==============================] - 2s 38ms/step - loss: 2.8751 - accuracy: 0.8136
Epoch 5/50
44/44 [==============================] - 2s 38ms/step - loss: 2.8447 - accuracy: 0.8156
Epoch 6/50
44/44 [==============================] - 2s 38ms/step - loss: 2.9564 - accuracy: 0.8083
Epoch 7/50
44/44 [==============================] - 2s 37ms/step - loss: 2.9550 - accuracy: 0.8084
Epoch 8/50
44/44 [==============================] - 2s 38ms/step - loss: 2.9032 - accuracy: 0.8118
Epoch 9/50
44/44 [==============================] - 2s 39ms/step - loss: 2.8825 - accuracy: 0.8131
Epoch 10/50
44/44 [==============================] - 2s 39ms/step - loss: 2.8633 - accuracy: 0.8144
Epoch 11/

In [12]:
extracted_model_demoX_train = model.predict(demoX_train)
extracted_model_demoX_test = model.predict(demoX_test)

In [13]:
extracted_model_demoX_train

array([[-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       ...,
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38],
       [-3.4028235e+38, -3.4028235e+38, -3.4028235e+38, ...,
        -3.4028235e+38, -3.4028235e+38, -3.4028235e+38]], dtype=float32)

Dietary Feature Extraction

In [14]:
dietData.shape

(8366, 44)

In [15]:
dietX_train, dietX_test, dietY_train, dietY_test = train_test_split(dietData, hypertensionData['Target'], test_size=0.33, random_state=42)

In [16]:
model = Sequential()
model.add(Conv1D(32, 3, activation='linear', input_shape=(44, 1)))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='linear'))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='linear'))
model.add(LeakyReLU(alpha=0.1))                  
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='linear', name='layer1'))
print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_3 (Conv1D)            (None, 42, 32)            128       
_________________________________________________________________
leaky_re_lu (LeakyReLU)      (None, 42, 32)            0         
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 21, 32)            0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 19, 64)            6208      
_________________________________________________________________
leaky_re_lu_1 (LeakyReLU)    (None, 19, 64)            0         
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 9, 64)             0         
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 7, 128)           

In [17]:
dietX_train = dietX_train.to_numpy()
dietX_train = dietX_train.reshape(dietX_train.shape[0], dietX_train.shape[1], 1)
dietX_test = dietX_test.to_numpy()
dietX_test = dietX_test.reshape(dietX_test.shape[0], dietX_test.shape[1], 1)
model.fit(dietX_train, dietY_train, epochs=50, batch_size=128)

Epoch 1/50
44/44 [==============================] - 1s 17ms/step - loss: 7.3040 - accuracy: 0.0000e+00
Epoch 2/50
44/44 [==============================] - 1s 18ms/step - loss: 7.1967 - accuracy: 0.0000e+00
Epoch 3/50
44/44 [==============================] - 1s 17ms/step - loss: 7.1896 - accuracy: 0.0000e+00
Epoch 4/50
44/44 [==============================] - 1s 17ms/step - loss: 7.1922 - accuracy: 0.0000e+00
Epoch 5/50
44/44 [==============================] - 1s 18ms/step - loss: 7.1823 - accuracy: 0.0000e+00
Epoch 6/50
44/44 [==============================] - 1s 18ms/step - loss: 7.1877 - accuracy: 0.0000e+00
Epoch 7/50
44/44 [==============================] - 1s 18ms/step - loss: 7.1855 - accuracy: 0.0000e+00
Epoch 8/50
44/44 [==============================] - 1s 17ms/step - loss: 7.1987 - accuracy: 0.0000e+00
Epoch 9/50
44/44 [==============================] - 1s 17ms/step - loss: 7.1982 - accuracy: 0.0000e+00
Epoch 10/50
44/44 [==============================] - 1s 17ms/step - loss:

In [18]:
extracted_model_dietX_train = model.predict(dietX_train)
extracted_model_dietX_test = model.predict(dietX_test)

In [19]:
extracted_model_dietX_train

array([[  288.05347 ,  -457.08002 ,   -48.67609 , ...,   814.994   ,
         -801.0034  , -1426.4456  ],
       [  304.0894  ,  -482.53235 ,   -51.385452, ...,   860.36816 ,
         -845.59924 , -1505.8563  ],
       [  307.9806  ,  -488.70868 ,   -52.043175, ...,   871.37854 ,
         -856.4206  , -1525.126   ],
       ...,
       [  299.35898 ,  -474.8038  ,   -50.85371 , ...,   845.21106 ,
         -830.5544  , -1479.806   ],
       [  283.76355 ,  -450.2707  ,   -47.9511  , ...,   802.8551  ,
         -789.0732  , -1405.2014  ],
       [  305.38544 ,  -484.57516 ,   -51.949898, ...,   863.8315  ,
         -848.49506 , -1510.721   ]], dtype=float32)

Examination Feature Extraction

In [20]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [21]:
exam_convert = examData.columns[examData.dtypes == object]

In [22]:
# Problem: Data type was String. we were not able to process data in NN
# Related to oral health
exam_convert

Index(['OHX02CTC', 'OHX03CTC', 'OHX04CTC', 'OHX05CTC', 'OHX06CTC', 'OHX07CTC',
       'OHX08CTC', 'OHX09CTC', 'OHX10CTC', 'OHX11CTC', 'OHX12CTC', 'OHX13CTC',
       'OHX14CTC', 'OHX15CTC', 'OHX18CTC', 'OHX19CTC', 'OHX20CTC', 'OHX21CTC',
       'OHX22CTC', 'OHX23CTC', 'OHX24CTC', 'OHX25CTC', 'OHX26CTC', 'OHX27CTC',
       'OHX28CTC', 'OHX29CTC', 'OHX30CTC', 'OHX31CTC', 'OHX02CSC', 'OHX03CSC',
       'OHX04CSC', 'OHX05CSC', 'OHX06CSC', 'OHX07CSC', 'OHX08CSC', 'OHX09CSC',
       'OHX10CSC', 'OHX11CSC', 'OHX12CSC', 'OHX13CSC', 'OHX14CSC', 'OHX15CSC',
       'OHX18CSC', 'OHX19CSC', 'OHX20CSC', 'OHX21CSC', 'OHX22CSC', 'OHX23CSC',
       'OHX24CSC', 'OHX25CSC', 'OHX26CSC', 'OHX27CSC', 'OHX28CSC', 'OHX29CSC',
       'OHX30CSC', 'OHX31CSC', 'OHX02RTC', 'OHX03RTC', 'OHX04RTC', 'OHX05RTC',
       'OHX06RTC', 'OHX07RTC', 'OHX08RTC', 'OHX09RTC', 'OHX10RTC', 'OHX11RTC',
       'OHX12RTC', 'OHX13RTC', 'OHX14RTC', 'OHX15RTC', 'OHX18RTC', 'OHX19RTC',
       'OHX20RTC', 'OHX21RTC', 'OHX22RTC', 'OHX23RTC

In [23]:
examData[exam_convert] = np.asarray(examData[exam_convert]).astype(str)

In [24]:
examData[exam_convert] = examData[exam_convert].replace(np.nan, -1)

In [25]:
from collections import defaultdict
d = defaultdict(LabelEncoder)

In [26]:
onehot = OneHotEncoder(handle_unknown = 'ignore')
examData[exam_convert] = examData[exam_convert].apply(lambda x: d[x.name].fit_transform(x))

In [27]:
examX_train, examX_test, examY_train, examY_test = train_test_split(examData, hypertensionData['Target'], test_size=0.33, random_state=42)

In [28]:
model = Sequential()
model.add(Conv1D(256, 3, activation='relu', input_shape=(138, 1)))
#model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='relu'))
#model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='relu'))
#model.add(LeakyReLU(alpha=0.1))                  
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='relu', name='layer1'))
print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_6 (Conv1D)            (None, 136, 256)          1024      
_________________________________________________________________
max_pooling1d_6 (MaxPooling1 (None, 68, 256)           0         
_________________________________________________________________
conv1d_7 (Conv1D)            (None, 66, 128)           98432     
_________________________________________________________________
max_pooling1d_7 (MaxPooling1 (None, 33, 128)           0         
_________________________________________________________________
conv1d_8 (Conv1D)            (None, 31, 64)            24640     
_________________________________________________________________
max_pooling1d_8 (MaxPooling1 (None, 15, 64)            0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 960)              

In [29]:
examX_train = examX_train.to_numpy()
examX_train = examX_train.reshape(examX_train.shape[0], examX_train.shape[1], 1)
examX_test = examX_test.to_numpy()
examX_test = examX_test.reshape(examX_test.shape[0], examX_test.shape[1], 1)
model.fit(examX_train, examY_train, epochs=10, batch_size=128)

Epoch 1/10
44/44 [==============================] - 10s 209ms/step - loss: nan - accuracy: 0.7330
Epoch 2/10
44/44 [==============================] - 9s 206ms/step - loss: nan - accuracy: 0.8165
Epoch 3/10
44/44 [==============================] - 9s 208ms/step - loss: nan - accuracy: 0.8143
Epoch 4/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8208
Epoch 5/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8245
Epoch 6/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8116
Epoch 7/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8105
Epoch 8/10
44/44 [==============================] - 9s 211ms/step - loss: nan - accuracy: 0.8242
Epoch 9/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8251
Epoch 10/10
44/44 [==============================] - 9s 207ms/step - loss: nan - accuracy: 0.8161


In [30]:
extracted_model_examX_train = model.predict(examX_train)
extracted_model_examX_test = model.predict(examX_test)

In [31]:
extracted_model_examX_train

array([[2.6775125e+38, 0.0000000e+00, 3.0074254e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00],
       [2.6775125e+38, 0.0000000e+00, 3.0074254e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00],
       [2.6775125e+38, 0.0000000e+00, 3.0074254e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00],
       ...,
       [          inf, 0.0000000e+00, 3.0074252e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00],
       [          inf, 0.0000000e+00, 3.0074252e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00],
       [          inf, 0.0000000e+00, 3.0074252e+38, ..., 0.0000000e+00,
        3.2514520e+38, 0.0000000e+00]], dtype=float32)

Laboratory Feature Extraction

In [32]:
labData.shape

(8366, 190)

In [33]:
labX_train, labX_test, labY_train, labY_test = train_test_split(labData, hypertensionData['Target'], test_size=0.33, random_state=42)

In [34]:
model = Sequential()
model.add(Conv1D(256, 3, activation='relu', input_shape=(190, 1)))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='relu'))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='relu'))    
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='relu', name='layer1'))
print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='adamax', metrics=['accuracy'])

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_9 (Conv1D)            (None, 188, 256)          1024      
_________________________________________________________________
max_pooling1d_9 (MaxPooling1 (None, 94, 256)           0         
_________________________________________________________________
conv1d_10 (Conv1D)           (None, 92, 128)           98432     
_________________________________________________________________
max_pooling1d_10 (MaxPooling (None, 46, 128)           0         
_________________________________________________________________
conv1d_11 (Conv1D)           (None, 44, 64)            24640     
_________________________________________________________________
max_pooling1d_11 (MaxPooling (None, 22, 64)            0         
_________________________________________________________________
flatten_2 (Flatten)          (None, 1408)             

In [35]:
labX_train = labX_train.to_numpy()
labX_train = labX_train.reshape(labX_train.shape[0], labX_train.shape[1], 1)
labX_test = labX_test.to_numpy()
labX_test = labX_test.reshape(labX_test.shape[0], labX_test.shape[1], 1)
model.fit(labX_train, labY_train, epochs=10, batch_size=128)

Epoch 1/10
44/44 [==============================] - 13s 272ms/step - loss: nan - accuracy: 0.8122
Epoch 2/10
44/44 [==============================] - 12s 273ms/step - loss: nan - accuracy: 0.8173
Epoch 3/10
44/44 [==============================] - 12s 272ms/step - loss: nan - accuracy: 0.8126
Epoch 4/10
44/44 [==============================] - 12s 272ms/step - loss: nan - accuracy: 0.8188
Epoch 5/10
44/44 [==============================] - 12s 272ms/step - loss: nan - accuracy: 0.8117
Epoch 6/10
44/44 [==============================] - 12s 272ms/step - loss: nan - accuracy: 0.8164
Epoch 7/10
44/44 [==============================] - 12s 272ms/step - loss: nan - accuracy: 0.8093
Epoch 8/10
44/44 [==============================] - 12s 273ms/step - loss: nan - accuracy: 0.8090
Epoch 9/10
44/44 [==============================] - 12s 273ms/step - loss: nan - accuracy: 0.8172
Epoch 10/10
44/44 [==============================] - 12s 271ms/step - loss: nan - accuracy: 0.8128


In [36]:
extracted_model_labX_train = model.predict(labX_train)
extracted_model_labX_test = model.predict(labX_test)

In [37]:
extracted_model_labX_train

array([[          inf, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                  inf, 0.0000000e+00],
       [          inf, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                  inf, 0.0000000e+00],
       [          inf, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
                  inf, 0.0000000e+00],
       ...,
       [          inf, 0.0000000e+00, 1.8312541e+38, ..., 0.0000000e+00,
                  nan, 0.0000000e+00],
       [          inf, 0.0000000e+00, 1.8312541e+38, ..., 0.0000000e+00,
                  nan, 0.0000000e+00],
       [          inf, 0.0000000e+00, 1.8312541e+38, ..., 0.0000000e+00,
                  nan, 0.0000000e+00]], dtype=float32)

Questionnaire Feature Extraction

In [38]:
questionData.shape

(8366, 783)

In [39]:
questionData.columns[questionData.dtypes == object]

Index(['SLQ300', 'SLQ310', 'SLQ320', 'SLQ330', 'SMDUPCA', 'SMD100BR'], dtype='object')

In [40]:
questionData.shape

(8366, 783)

In [41]:
questionData.drop(questionData.columns[questionData.dtypes == object], axis = 1, inplace=True)

In [42]:
questionX_train, questionX_test, questionY_train, questionY_test = train_test_split(questionData, hypertensionData['Target'], test_size=0.33, random_state=42)

In [43]:
model = Sequential()
model.add(Conv1D(32, 3, activation='linear', input_shape=(777, 1)))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='linear'))
model.add(LeakyReLU(alpha=0.1))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='linear'))
model.add(LeakyReLU(alpha=0.1))                  
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='linear', name='layer1'))
print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='Ftrl', metrics=['accuracy'])

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_12 (Conv1D)           (None, 775, 32)           128       
_________________________________________________________________
leaky_re_lu_3 (LeakyReLU)    (None, 775, 32)           0         
_________________________________________________________________
max_pooling1d_12 (MaxPooling (None, 387, 32)           0         
_________________________________________________________________
conv1d_13 (Conv1D)           (None, 385, 64)           6208      
_________________________________________________________________
leaky_re_lu_4 (LeakyReLU)    (None, 385, 64)           0         
_________________________________________________________________
max_pooling1d_13 (MaxPooling (None, 192, 64)           0         
_________________________________________________________________
conv1d_14 (Conv1D)           (None, 190, 128)         

In [44]:
questionX_train = questionX_train.to_numpy()
questionX_train = questionX_train.reshape(questionX_train.shape[0], questionX_train.shape[1], 1)
questionX_test = questionX_test.to_numpy()
questionX_test = questionX_test.reshape(questionX_test.shape[0], questionX_test.shape[1], 1)
model.fit(questionX_train, questionY_train, epochs=50, batch_size=128)

Epoch 1/50
44/44 [==============================] - 12s 247ms/step - loss: nan - accuracy: 0.7861
Epoch 2/50
44/44 [==============================] - 11s 245ms/step - loss: 2.9044 - accuracy: 0.8117
Epoch 3/50
44/44 [==============================] - 11s 247ms/step - loss: 2.8450 - accuracy: 0.8156
Epoch 4/50
44/44 [==============================] - 11s 247ms/step - loss: 2.8724 - accuracy: 0.8138
Epoch 5/50
44/44 [==============================] - 11s 247ms/step - loss: 2.8943 - accuracy: 0.8124
Epoch 6/50
44/44 [==============================] - 11s 248ms/step - loss: 2.8122 - accuracy: 0.8177
Epoch 7/50
44/44 [==============================] - 11s 249ms/step - loss: 2.8078 - accuracy: 0.8180
Epoch 8/50
44/44 [==============================] - 11s 248ms/step - loss: 2.8799 - accuracy: 0.8133
Epoch 9/50
44/44 [==============================] - 11s 248ms/step - loss: 2.8208 - accuracy: 0.8171
Epoch 10/50
44/44 [==============================] - 11s 248ms/step - loss: 2.8423 - accuracy:

In [45]:
extracted_model_questionX_train = model.predict(questionX_train)
extracted_model_questionX_test = model.predict(questionX_test)

In [46]:
extracted_model_questionX_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

Merge Hypertension features with other extracted features

In [47]:
from keras.utils.np_utils import to_categorical
from keras.optimizers import RMSprop,Adam

In [48]:
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(hypertensionData['Target'])
encoded_Y = encoder.transform(hypertensionData['Target'])
# convert integers to dummy variables (i.e. one hot encoded)
y = to_categorical(encoded_Y)

In [49]:
hypertensionX_train, hypertensionX_test, dataY_train, dataY_test = train_test_split(hypertensionData.drop('Target', axis=1), y, 
                                                                                    test_size=0.33, random_state=42)

In [50]:
hypertensionX_train = hypertensionX_train.to_numpy()
hypertensionX_test = hypertensionX_test.to_numpy()

In [51]:
dataX_train = np.concatenate((extracted_model_demoX_train, extracted_model_dietX_train, extracted_model_examX_train, 
                              extracted_model_labX_train, extracted_model_questionX_train, hypertensionX_train),
                             axis = 1)

In [52]:
dataX_train.shape

(5605, 817)

In [53]:
dataX_test = np.concatenate((extracted_model_demoX_test, extracted_model_dietX_test, extracted_model_examX_test, 
                             extracted_model_labX_test, extracted_model_questionX_test, hypertensionX_test),
                             axis = 1)

In [54]:
dataX_test.shape

(2761, 817)

In [55]:
model = Sequential()
model.add(Conv1D(256, 5, activation='relu', input_shape=(817, 1)))
model.add(MaxPooling1D(2))
model.add(Conv1D(128, 3, activation='relu'))
model.add(MaxPooling1D(2))
model.add(Conv1D(64, 3, activation='relu'))    
model.add(MaxPooling1D(2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(2, activation='softmax'))
print(model.summary())
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1d_15 (Conv1D)           (None, 813, 256)          1536      
_________________________________________________________________
max_pooling1d_15 (MaxPooling (None, 406, 256)          0         
_________________________________________________________________
conv1d_16 (Conv1D)           (None, 404, 128)          98432     
_________________________________________________________________
max_pooling1d_16 (MaxPooling (None, 202, 128)          0         
_________________________________________________________________
conv1d_17 (Conv1D)           (None, 200, 64)           24640     
_________________________________________________________________
max_pooling1d_17 (MaxPooling (None, 100, 64)           0         
_________________________________________________________________
flatten_4 (Flatten)          (None, 6400)             

In [56]:
dataX_train = dataX_train.reshape(dataX_train.shape[0], dataX_train.shape[1], 1)
dataX_test = dataX_test.reshape(dataX_test.shape[0], dataX_test.shape[1], 1)

In [57]:
tf.config.run_functions_eagerly(True)

In [58]:
model.fit(dataX_train, dataY_train, epochs=10, batch_size=128)

Epoch 1/10


/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "


44/44 [==============================] - 52s 1s/step - loss: nan - accuracy: 0.8083
Epoch 2/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8205
Epoch 3/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8108
Epoch 4/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8287
Epoch 5/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8163
Epoch 6/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8152
Epoch 7/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8103
Epoch 8/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8213
Epoch 9/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8213
Epoch 10/10
44/44 [==============================] - 51s 1s/step - loss: nan - accuracy: 0.8152


In [59]:
y_pred = model.predict(dataX_test)
#Converting predictions to label
pred = list()
for i in range(len(y_pred)):
    pred.append(np.argmax(y_pred[i]))
#Converting one hot encoded test label to label
test = list()
for i in range(len(dataY_test)):
    test.append(np.argmax(dataY_test[i]))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "


In [60]:
model.predict(dataX_train)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "


array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]], dtype=float32)

In [61]:
model.predict(dataX_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/data/ops/dataset_ops.py:3504: UserWarning: Even though the tf.config.experimental_run_functions_eagerly option is set, this option does not apply to tf.data functions. tf.data functions are still traced and executed as graphs.
  "Even though the tf.config.experimental_run_functions_eagerly "


array([[nan, nan],
       [nan, nan],
       [nan, nan],
       ...,
       [nan, nan],
       [nan, nan],
       [nan, nan]], dtype=float32)

In [62]:
from sklearn.metrics import accuracy_score
a = accuracy_score(pred,test)
print('Accuracy is:', a*100)

Accuracy is: 80.98515030785947
